var rule = {
  类型:'影视',
  title:'酷八影视',
  host:'http://k8.8itv.cn/',
  url:'/index.php/vod/show/id/fyclass/page/fypage.html',
  searchUrl:'/index.php/vod/search.html?wd=**&submit=',
  searchable:2,
  quickSearch:0,
  filterable:1,
  filter:'',
  filter_url:'',
  filter_def:{},
  headers:{
      'User-Agent':'MOBILE_UA',
  },
  timeout:5000,
  class_parse:'.hl-nav.hl-text-site li;a&&Text;a&&href;.*/(.*)\.html',
  cate_exclude:'体育',
  play_parse:true,
  lazy:$js.toString(()=>{
    input = {parse:1,url:input,js:''};
  }),
  double:true,
  推荐:'ul.hl-vod-list;li;*;*;*;*',
  一级:'.hl-vod-list.clearfix li;a&&title;a&&data-original;.hl-pic-text&&Text;a&&href',
  二级:{
    title:'.hl-full-box.clearfix ul li:eq(0)&&Text',
    img:'.hl-full-box.clearfix ul li:eq(2)&&Text',
    desc:'主要信息;.hl-full-box.clearfix ul li:eq(5)&&Text;.hl-full-box.clearfix ul li:eq(6)&&Text;.hl-full-box.clearfix ul li:eq(3)&&Text;.hl-full-box.clearfix ul li:eq(4)&&Text',
    content:'.hl-full-box.clearfix ul li:eq(12)&&Text',
    tabs:'.hl-plays-from.hl-tabs.swiper-wrapper.clearfix a',
    lists:'#hl-plays-list:eq(#id)&&a',
    tab_text:'body&&Text',
    list_text:'body&&Text',
    list_url:'a&&href',
    list_url_prefix: '',
  },
  搜索:'li.hl-list-item.hl-col-xs-12;.hl-item-content a&&title;.hl-item-pic a&&data-original;.hl-item-pic span&&Text;.hl-item-pic a&&href',
}