var rule = {
  title: '爱看影视',
  host: 'https://ilookys.com/',
  url: '/index.php/vod/type/id/fyclass.html',
  searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  class_name:'电影&电视剧&动漫&综艺&短剧',
    class_url:'20&21&22&23&24',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input;\n  }",
  limit: 60,
  double:false,
  推荐: '.module-items a;.module-poster-item-info&&Text;img&&data-original;.module-item-note&&Text;a&&href',
  一级: '.module-items a;.module-poster-item-info&&Text;img&&data-original;.module-item-note&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.tag-link&&Text',
    img: '.module-item-pic&&img&&data-data-original',
    desc: '.video-info-items:eq(3)&&Text;.tag-link:eq(2)&&Text;.tag-link:eq(1)&&Text;.video-info-items:eq(1)&&Text;.video-info-items:eq(0)&&Text',
    content: '.module-info-introduction-content&&Text',
    tabs: '.module-tab-item',
    lists: '.module-play-list-content:eq(#id)&&a',
    tab_text: 'div--small&&Text',
  },
  搜索: '.module-items .module-card-item;.module-card-item-title&&Text;a&&.module-item-pic&&img&&data-original;.module-info-item-content&&Text;a&&href',
}