var rule = {
  title: '爱看4k影院',
  host: 'https://ikan4k.com/',
  url: '/index.php/vod/show/fyfilter.html',
  searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
  searchable: 2,
  quickSearch: 0,
   filterable: 1,
   filter: 'H4sIAAAAAAAAA+2Z3U7bSBTH7/cpqlwjgRM++wb7DKtepG2kRdvtSsBWQlUlIB8kgSYBQWg24asQAjSBBFIKDiYv4xk7b7F2ZvCcOWPURC3Sos3t7//PmfGZ8ZzjyfuAFnj+2/vAH5H5wPNngVfhucivrwNDgbfhPyMusBotsrPigHfhN3+7xPG+dQUSP+5Ej+/lZ4F3Lgx8GLqX08emUbJSy542/Xp4HOj5EklVkD4hdCvZoNE40ieBXlkjNy2kTwmdLuboQh7p2giYQKqiDqBpIELyk6mnsCEIpqCfEmMTGYJgjubtkZVLYMOUlCR6+8Xa+EqMBvSEnHm+cF33q/ImPDsLFoXN/cFFuZfVRekm3RO6YYc5RJlHJg5RepGJQ7QH8HAMooXEwzGIFgtHYhAtGJ4Tg57Jrh2R1VNk4lDMKX1uGdjEIXw6awNPnENhKi+rT8ehmHjtyLzbwxNnUERKrHcKJzgSgyLSzqnzwDgSg8K0VLXya9jEoDBF03TpH2xiUOSplSXxa5wnBj1TZ3udfiojE4diuPyyndLxcAyKFNydoXeFZ8Hjwpo9tA+UDcOgMGUSJHuBTQyKDdPOOYuKNwyDYHFKdBunlENhirWtLzgRHIqUGmtWq+T7mJIknQ/hmUgYHg+lOlnVHz4euKweD4eVTiHhCW7UYc7Eah4V6PW57OEMJL9Ob+5QHMbEc95lSNGQPZyJTXG5qXg4E8uz0lA8nIk4W2VaqqI4jInn2j1R4nAG9t83xcMZmHPdZ851Oc7HOtGPUBzGRJxY1kk9SZ6gUB4WGSi3rWzNShVQEjwMTqw9utJ2fo+G9rBwxq/MVh7ZGJM23nwkPAM33k3TbBkPbjy6ddXZavpsvOBIcNTDbszhLoF6SNFDkh5U9KCka4quSfqIoo9AXZvCujYl6ZOKPinpE4o+Ienjij4u6WOKPibpSv40KX+akj9Nyp+m5E+T8qcp+dOk/GlK/jTUw7ychxuF7YfMOtGzPtsFbZSX88Nz084PRWOl67S+AfXfp+dmwStxHiPJBNRnX/01E3En9GLol0DwcTreomHqFdhfuf0iyLJzRjqnIDaMSueUe+QgA1hnWq24ZyQyjP9Qs+j3JL0Uz566LVbmyeIViWZ9OwAu9dehkrMrotewicG+e7jvd6g99XA9dag9NRw9NVXmzb7acHAIerg4LZzjJWJQzGkzobaMHMKuRF0WDh8qGjyST9Xor13x26CJuPMjVJ4Y66ug/6xmppcGo7eG5/vNQ08NT77uFHWyvY9CeXhQ6AeF/n9Q6Ed/pNA/XOK7tzbSnY5axFWPWsdVzzh+M308E49zN+TWhdiuT7FwYH+XNVa0Zu8vYBODYrjMsZVL4OEYFKbcjlVVbioY7O9ixM5t2xncrXAohtvbJ0XcV3DYX8tAS7rPPQyD/d0s9NRmkbqzAk08JwYlU/nSx+RAsXaHd+YtvvbhELQxuyRZVNqYLgSv7gWp5XCHwqAYrpimBXztwyHIeIO0t5SMd2H/zcegkg0q2dOrZKGfXcm63bLVuoW3rm51AVuIfa/6eOCfJN1q5+MBS8GqnY8n9DiVrLOQsiq4/nDYX7mzz9p2PYlPaAZFpPUaTeNrXQ5BnuL0Gn/UcQg+WS7NG3xkcgi/IzoHeOIcCpN+Ss52sIlBMafihc+dO4Mi0sYubSoVn0GwU65pMmvq62o9kySR2OZn54sWJ5ZBEbWxZC+u4ngMDo70wZH+1I/0R/rjvXzZ+bxGF1espPyfMsgkyX60jaqVNNBVYgishh1bo80d9F+h6wEr2n3TDqyTtn2VljxjcCz33tBsFeBfnK4H7CwrU3fidKIGuV6SPBNP6kX/L260D/8CSH0RjuEhAAA=',
   filter_url: "{{fl.area}}/{{fl.by}}/{{fl.class}}/{{fl.cateId}}/page/fypage/{{fl.year}}.html",
   filter_def: {
'1': {cateId: 'id/1'},'2': {cateId: 'id/2'},'3': {cateId: 'id/3'},'31': {cateId: 'id/31'},'4': {cateId: 'id/4'}},
  class_parse: '.nav-menu-items&&li;a&&Text;a&&href;.*/(.*?).html',
  play_parse: true,
  lazy: 'js:eval(unescape(base64Decode("anM6CgkJcGRmaCA9IGpzcC5wZGZoOyBwZGZhID0ganNwLnBkZmE7IHBkID0ganNwLnBkOwoJCWxldCBkb2N1bWVudCA9IHt9OwoJCWxldCBuYXZpZ2F0b3IgPSB7CgkJCXVzZXJBZ2VudDogTU9CSUxFX1VBLAoJCX07CgkJbGV0IGJhc2U2NGRlY29kZSA9IGJhc2U2NERlY29kZTsKCQlsZXQgcG4gPSAnJywgbm93ID0gJycsIG5leHRQYWdlID0gJycsIHByZVBhZ2UgPSAnJywgbmV4dCA9ICcnLCB2aWQgPSAnJywgdmZyb20gPSAnJywgdnBhcnQgPSAnJywgc3JjVXJsID0gJyc7CgkJZXZhbChyZXF1ZXN0KEhPU1QgKyAiL2pzL3BsYXkuanMiKSk7CgkJbGV0IGh0bWwgPSByZXF1ZXN0KGlucHV0KTsKCQlldmFsKHBkZmgoaHRtbCwgIi5tYi0yJiZzY3JpcHQmJkh0bWwiKS5yZXBsYWNlQWxsKCd2YXIgJywnJykpOwoJCWV2YWwocGRmaChodG1sLCAiLm1iLTImJnNjcmlwdCwxJiZIdG1sIikucmVwbGFjZUFsbCgndmFyICcsJycpLnNwbGl0KCJkb2N1bWVudCIpWzBdKTsKCQlsZXQgcGFyc2VIdG1sID0gcmVxdWVzdChIT1NUICsgIi9qcy9wbGF5ZXIvIiArIHBuICsgIi5odG1sIik7CgkJbGV0IHBhcmVudCA9IHsKCQkJbm93OiBub3csCgkJCW5leHRQYWdlOiBuZXh0UGFnZSwKCQkJbmV4dDogbmV4dCwKCQkJdmlkOiB2aWQsCgkJCXZmcm9tOiB2ZnJvbSwKCQkJdnBhcnQ6IHZwYXJ0LAoJCX07CgkJbGV0IHBhcmpzID0gcGRmaChwYXJzZUh0bWwsICJib2R5JiZzY3JpcHQmJkh0bWwiKTsKCQlldmFsKCJzcmNVcmwgPSAnIiArIHBkZmgocGFyanMsICJpZnJhbWUmJnNyYyIpICsgIiciKTsKCQlpZiAoc3JjVXJsLmluZGV4T2YoIj91cmw9IikgPiAtMSB8fCBzcmNVcmwuaW5kZXhPZigiP3VpZD0iKSA+IC0xKSB7CgkJCWlucHV0ID0ge2p4OjAsIHVybDpzcmNVcmwuc3BsaXQoIj0iKVsxXSwgcGFyc2U6MH0KCQl9IGVsc2UgewoJCQlsZXQgcHVybCA9IHNyY1VybC5zcGxpdCgiPSIpWzFdLnNwbGl0KCIsIilbMV07CgkJCWlucHV0ID0ge2p4OjAsIHVybDpwdXJsLCBwYXJzZTowfQoJCX0=")))',
  cate_exclude: "伦理片|资讯",
   double: false,
  limit: 6,
  推荐: '.module-list;.module-items&&.module-item;a&&title;img&&data-src;.module-item-text&&Text;a&&href',
  double: true,
  一级: '.module-items .module-item;a&&title;img&&data-src;.module-item-text&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.tag-link&&Text',
    img: '.module-item-pic&&img&&data-src',
    desc: '.video-info-items:eq(0)&&Text;.video-info-items:eq(1)&&Text;.video-info-items:eq(2)&&Text;.video-info-items:eq(3)&&Text',
    content: '.vod_content&&Text',
    tabs: '.module-tab-item',
    lists: '.module-player-list:eq(#id)&&.scroll-content&&a',
  },
  搜索: '.module-items .module-search-item;a&&title;img&&data-src;.video-serial&&Text;a&&href;.video-info-item&&Text',
}